# Generated by Django 2.2.7 on 2019-11-05 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='creation_date')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=1)),
                ('likes', models.IntegerField(default=0)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catface.Cat')),
            ],
        ),
    ]
