# Generated by Django 2.2.7 on 2019-11-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='picturelink',
            field=models.CharField(default='static/images/catface150X150.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
